services:
  web:
    build:
      context: angular
      target: builder
      args:
        API_URL: "http://cars.cprogroup.ru"
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules
