services:
  app:
    build:
      context: ./angular
      args:
        API_URL: "http://cars.cprogroup.ru"
    ports:
      - 4200:80
    volumes:
      - ./angular:/app
      - /project/node_modules
